# Starter pipeline
trigger:
- main

pool:
  vmImage: 'Ubuntu-16.04'
strategy:
  matrix:
    Python38:
      python.version: '3.8'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
- script: echo Simple Caesar Program
  displayName: 'Run a multi-line script'

- script: |
    pip install xmlrunner
    pip install unittest_xml_reporting
    python test_xmlrunner.py
  displayName: 'Run xmlrunner'
- script: |
    pip install coverage
    coverage run test_runner.py


