# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'macOS-10.13'
strategy:
  matrix:
    Python38:
      python.version: '3.8'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    pip install xmlrunner
    pip install unittest_xml_reporting
    python test_xmlrunner.py
  displayName: 'Run xmlrunner'
- script: |
    pip install coverage
    coverage run test_runner.py
    coverage xml –o coverage.xml
- task: PublishTestResults@2
  inputs:
    testResultsFiles: 'coverage.xml'
    testRunTitle: '$(Agent.OS) - $(Build.DefinitionName) - Python $(python.version)'
  condition: succeededOrFailed()

