# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    pip install xmlrunner
    pip install unittest_xml_reporting
    python test_xmlrunner.py
    pip install coverage
    coverage run test_runner.py
  displayName: 'Run a multi-line script'
